### ISSUE TITLE
Context namespace element 'component-scan' and its parser class [org.springframework.context.annotation.ComponentScanBeanDefinitionParser] are only available on JDK 1.5 and higher

### ISSUE THREAD

**Issue by buffcleb** [Jasig/SSP#14]
I've been trying to get 2.8 to run for several days... Im not a java developer... I'm setting this up for a DBA and I keep running into this error... 

27-Sep-2017 14:28:43.296 SEVERE [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log StandardWrapper.Throwable
org.springframework.beans.factory.BeanDefinitionStoreException: Unexpected exception parsing XML document from ServletContext resource [/WEB-INF/spring-servlet.xml]; nested exception is java.lang.IllegalStateException: Context namespace element 'component-scan' and its parser class [org.springframework.context.annotation.ComponentScanBeanDefinitionParser] are only available on JDK 1.5 and higher

after digging around I figured out it had to do with some spring jar files not supporting java 1.8 but I can not figure out how to get around it.... any ideas???

**Comment by buffcleb** [comment]
I should not I'm running idk 1.8 as required for SSP 2.8

**Comment by pspaude** [comment]
You are correct that error does relate to the Java version and spring files. However, it's expected for a few old portlets in SSP-Platform(uPortal) like the NotificationPortlet, but shouldn't occur for elements in SSP itself. 

If you could, paste more of the error statement, the trace will show which area of the application this issue is affecting. I assume you have Java 1.8 installed and the JAVA_HOME variable points to it? Also, if you could give any other info around the issues you're seeing that'd be great. For example, can you reach the login page and login? 


-Paul

**Comment by buffcleb** [comment]
[Archive.zip](https://github.com/Jasig/SSP/files/1345690/Archive.zip)

right now nothing works... it's listening on port 8080 but beyond that I'm getting nothing... I zipped up the logs directory along with the output from "ant -Dmaven.test.skip=true clean initportal"

**Comment by buffcleb** [comment]
here's the env vars I have for the user running tomcat : 

export JAVA_HOME=/app/jdk/jdk1.8.0_141
export JDK_HOME=/app/jdk/jdk1.8.0_141
export INSTALL4J_JAVA_HOME=/app/jdk/jdk1.8.0_141
export JDK_PREFER=8
export MAVEN_HOME=/app/maven/latest/
export M2_HOME=/app/maven/latest/
export ANT_HOME=/app/ant/latest/
export SSP_CONFIGDIR=/app/ssp/ssp-local
export TOMCAT_HOME=/app/tomcat/latest
PATH=$PATH:$HOME/.local/bin:$HOME/bin:$JAVA_HOME/bin:$PATH:/app/maven/latest/bin:/app/ant/latest/bin:/app/Sencha

**Comment by pspaude** [comment]
The logs and environment look good, it appears SSP is up and running normally. Have you tried: "http://localhost:8080/ssp-platform"? If that doesn't work then try "http://127.0.0.1:8080/ssp-platform". 


-Paul

**Comment by buffcleb** [comment]
thanks for the quick response... the box is remote so I can't do either of those directly... I tried remotely using http://machinename:8080/ssp-platform and when that didn't work I tried from the local machine using nc :

nc localhost 8080
GET /ssp-platform

8080 never returns... I know its listening because this is what I get with 8081

nc localhost 8081
Ncat: Connection refused.
