### ISSUE TITLE
Internationalization and localization (Multi-language support)

### ISSUE THREAD

**Issue by ecabrerar** [Jasig/SSP#6]
It would be great if SSP can offer its content in languages and formats tailored to the audience.

**Comment by pspaude** [comment]
I know this request is old, but there have been recent feature additions that answer this question. 

SSP is an Open Source product funded by participating schools and owned by a community comprising of all schools who implement SSP. Recently an organization in the U.K. funded internationalization. This ticket [SSP-3111] (https://issues.jasig.org/browse/SSP-3111) in SSP's JIRA tracks that goal. To date, many parts of [SSP] (https://github.com/Jasig/SSP) have been internationalized and [SSP-Platform] (https://github.com/Jasig/SSP-Platform) is nearly complete. The internationalization feature also has an additional benefit in the form of label and message customization with very little source code modification.

If you have further questions or comments we'd be happy to answer them on our user or dev [email lists] (https://wiki.jasig.org/display/SSP/SSP+Email+Lists)
